id: I5B351180
legacy_id: P010359
ocr_import_info:
  bdrc_scan_id: W1KG3172
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:28:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:56:13.734819+00:00'
last_modified: 2022-08-31 22:56:36.431044
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3172
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3172
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་མཆན་འགྲེལ།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.919188130757633
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG3207:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3207
      total_pages: 1024
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3207.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.919188130757633
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
