id: I5B351180
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:35:22+00:00'
last_modified: '2022-06-08T13:00:41.380144+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3172
  title: མངོན་པ་མཛོད་ཀྱི་མཆན་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E9A:
      image_group_id: I1KG3207
      title: ''
      total_pages: 1024
      order: 1
      base_file: 6E9A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
