id: P010359
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG3172
  title: མངོན་པ་མཛོད་ཀྱི་མཆན་འགྲེལ
  author: ''
  volumes:
    6964223beb7b415097e76578aca047f4:
      image_group_id: I1KG3207
      title: ''
      volume_number: 1
      total_pages: 1024
      base_file: v001.txt
